# Generated by Django 6.0.6 on 2026-06-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('Bus', 'Bus'), ('Minibús', 'Minibús'), ('Van', 'Van'), ('Micro', 'Micro'), ('Taxi', 'Taxi')], default='Bus', max_length=20, verbose_name='Tipo')),
                ('capacidad', models.PositiveIntegerField(default=40, verbose_name='Capacidad')),
                ('precio_pasaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio pasaje')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Mantenimiento', 'Mantenimiento')], default='Activo', max_length=20, verbose_name='Estado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.route', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['name'],
            },
        ),
    ]
