# Generated by Django 6.0.6 on 2026-06-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('origin', models.CharField(max_length=100, verbose_name='Origen')),
                ('destination', models.CharField(max_length=100, verbose_name='Destino')),
                ('tarifa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarifa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='routes/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['name'],
            },
        ),
    ]
